/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   main.cpp
 * Author: Ivan Beltran-Salazar
 *Purpose: Create program that calculates total sales
 * Created on September 20, 2016, 8:11 PM
 */

#include <cstdlib>
#include <iostream>
#include <iomanip>
using namespace std;
//User Libraries

//Global Constants
const float PERCENT=100;
//Function prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declaration of Variables
    float eaCsale=4600000, totSale;
    int perSale=62;
    //Input values
    totSale=eaCsale/(perSale/PERCENT);
    //Process values -> Map inputs to Outputs
    
    //Display Output
    cout<<"The amount of sales by The East Coast division is "<<setprecision(6)<<eaCsale<<"."<<endl;
    cout<<"The East Coast divison generates "<<setprecision(6)<<perSale<<"% this year."<<endl;
    cout<<"The total amount of sales generated by The East Coast company is "<<setprecision(6)<<totSale<<"."<<endl;
    //Exit Program
    return 0;
}

